[package]
name = "commands"
version = "0.1.0"
edition = "2021"
description = "Small helpers to make dealing with CLIs less annoying"
authors = ["Natalie Jameson <natalie@natalie.wtf>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
async-trait = "*"
derivative = "*"
dirs = "*"
gazebo = "*"
hostname = "*"
itertools = "*"
log = "*"
serde = {version="*", features = ["derive"]}
serde_json = "*"
tee = { git = "ssh://git@github.com/nataliejameson/tee", version = "0.1.0" }
tempfile = "*"
thiserror = "*"
tracing = "*"
